# 设备的主机名
hostname = ""
dhcp = true
ipv4 = ""
listeners = [ "tcp://0.0.0.0:11010", "quic://0.0.0.0:11020", "udp://0.0.0.0:11010" ]
rpc_portal = "0.0.0.0:15888"

[network_identity]
network_name = ""
network_secret = ""

[[peer]]
uri = "https://raw.githubusercontent.com/710850609/fpk-EasyTier-Lite/refs/heads/main/peers/peer-1.txt"
[[peer]]
uri = "https://raw.githubusercontent.com/710850609/fpk-EasyTier-Lite/refs/heads/main/peers/peer-2.txt"
[[peer]]
uri = "https://raw.githubusercontent.com/710850609/fpk-EasyTier-Lite/refs/heads/main/peers/peer-3.txt"
[[peer]]
uri = "https://raw.githubusercontent.com/710850609/fpk-EasyTier-Lite/refs/heads/main/peers/peer-4.txt"
[[peer]]
uri = "https://raw.githubusercontent.com/710850609/fpk-EasyTier-Lite/refs/heads/main/peers/peer-5.txt"

[flags]
# 使用 KCP 代理 TCP 流，提高在 UDP 丢包网络上的延迟和吞吐量 (KCP 代理会优先于 QUIC 代理生效)
enable_kcp_proxy = true
# 使用 QUIC 代理 TCP 流，提高在 UDP 丢包网络上的延迟和吞吐量
enable_quic_proxy = true
# 延迟优先模式，将尝试使用最低延迟路径转发流量，默认使用最短路径
latency_first = true
# 将连接器的套接字绑定到物理设备以避免路由问题
bind_device = true
# 通过系统内核转发子网代理数据包，禁用内置NAT
proxy_forward_by_system = true
# 不允许使用了与本网络不相同的网络名称和密码的节点通过本节点进行握手或中转
private_mode = true
# 禁用UDP打洞功能
disable_udp_hole_punching = false
# 使用多线程运行
multi_thread = true
