#!/bin/bash
set -e
source /var/apps/${TRIM_APPNAME}/cmd/common.sh

PID_FILE="${TRIM_PKGVAR}/app.pid"
RESTART_FLAG_FILE="${TRIM_PKGVAR}/.restart"
RUNNING_FLAG_FILE="${TRIM_PKGVAR}/.run"

# write the command to start your program here 
CMD="${BIN_DIR}/easytier-core --config-file ${CFG_FILE}"

start_process() {
    if status; then
        return 0
    fi

    log_msg "Starting process ..."
    log_msg "CMD = ${CMD}"
    # run cmd to start process
    bash -c "${CMD}" >> /dev/null 2>&1 &
    # write pid to pidfile
    printf "%s" "$!" > ${PID_FILE}
    # touch "${KEEP_RUNNING_FILE}"
    # log_msg "CMD = ${CMD}"
    # log_msg "pid = $!"
    return 0
}

stop_process() {
    log_msg "Stopping process ..."

    if [ -r "${PID_FILE}" ]; then
        pid=$(head -n 1 "${PID_FILE}" | tr -d '[:space:]')
        
        log_msg "pid=${pid}"
        if ! check_process "${pid}"; then
            # process not exist, delete pidfile
            rm -f "${PID_FILE}"
            # rm -f "${KEEP_RUNNING_FILE}"
            log_msg "remove pid file 1"
            return
        fi

        log_msg "send TERM signal to PID:${pid}..."
        kill -TERM ${pid} >> ${LOG_FILE} 2>&1

        local count=0
        while check_process "${pid}" && [ $count -lt 10 ]; do
            sleep 1
            count=$((count + 1))
            log_msg "waiting process terminal... (${count}s/10s)"
        done

        if check_process "${pid}"; then
            log_msg "send KILL signal to PID:${pid}..."
            kill -KILL "${pid}"
            sleep 1
            rm -f "${PID_FILE}"
            # rm -f "${KEEP_RUNNING_FILE}"
        else
            log_msg "process killed... "
        fi
    fi

    return 0
}

check_process() {
    local pid=$1
    if kill -0 "${pid}" 2>/dev/null; then
        return 0  # process exist
    else
        return 1  # process not exist
    fi
}

status() {
    if [ -f "${PID_FILE}" ]; then
        pid=$(head -n 1 "${PID_FILE}" | tr -d '[:space:]')
        if check_process "${pid}"; then
            return 0
        else
            # Process is not running but pidfile exists - clean it up
            rm -f "${PID_FILE}"
        fi    
    fi

    return 1
}


fn_service() {
    local action="$1"
    local cmd="cd ${SCRIPT_PATH} && ${SCRIPT_PATH}/.venv/bin/python3 -m utils.fn_service ${action}"
    # 在子 shell 中执行，捕获 stdout 和退出码
    local result
    result=$(eval "$cmd" 2>&1)   # 2>&1 将 stderr 也合并到 stdout（根据需求可选）
    local return_code=$?
    # 处理 echo 默认不支持\n换行
    msg=$(printf "invoke ${action}\n  cmd: ${cmd}\n  return_code: ${return_code}\n  result : ${result}")
    log_msg "${msg}"
    if [[ $return_code != 0 ]] && [[ ! ($action == 'status' && $return_code == 3) ]]; then
      echo $(printf "调用 ${action} 返回结果码 ${return_code} \n${result}") > $TRIM_TEMP_LOGFILE
    fi
    return $return_code
}

case $1 in
start)
    # run start command. exit 0 if success, exit 1 if failed
#    start_process
    fn_service start
    ;;
stop)
    # run stop command. exit 0 if success, exit 1 if failed
#    stop_process
    fn_service stop
    ;;
status)
    # check application status command. exit 0 if running, exit 3 if not running
    exit $(fn_service status)
#    if status; then
#        exit 0
#    elif [ -f "${RESTART_FLAG_FILE}" ]; then
#        # 优先根据restart_flag文件判断是否运行
#        exit 0
#    else
#        exit 3
#    fi
    ;;
*)
    exit 1
    ;;
esac